import { Component, Input, OnInit } from '@angular/core';
import { Items } from '../Items';

@Component({
  selector: 'app-repositorio',
  templateUrl: './repositorio.component.html',
  styleUrls: ['./repositorio.component.css']
})
export class RepositorioComponent implements OnInit {

  @Input() repositorio: Items = {
    id: 0,
    node_id: '',
    name: '',
    full_name: '',
    private: false,
    owner: {
      login: '',
      id: 0,
      node_id: '',
      avatar_url: '',
      gravatar_id: '',
      url: '',
      html_url: '',
      followers_url: '',
      following_url: '',
      gists_url: '',
      starred_url: '',
      subscriptions_url: '',
      organizations_url: '',
      repos_url: '',
      events_url: '',
      received_events_url: '',
      type: '',
      site_admin: false
    },
    html_url: '',
    description: '',
    fork: false,
    url: '',
    forks_url: '',
    keys_url: '',
    collaborators_url: '',
    teams_url: '',
    hooks_url: '',
    issue_events_url: '',
    events_url: '',
    assignees_url: '',
    branches_url: '',
    tags_url: '',
    blobs_url: '',
    git_tags_url: '',
    git_refs_url: '',
    trees_url: '',
    statuses_url: '',
    languages_url: '',
    stargazers_url: '',
    contributors_url: '',
    subscribers_url: '',
    subscription_url: '',
    commits_url: '',
    git_commits_url: '',
    comments_url: '',
    issue_comment_url: '',
    contents_url: '',
    compare_url: '',
    merges_url: '',
    archive_url: '',
    downloads_url: '',
    issues_url: '',
    pulls_url: '',
    milestones_url: '',
    notifications_url: '',
    labels_url: '',
    releases_url: '',
    deployments_url: '',
    created_at: "",
    updated_at: "",
    pushed_at: "",
    git_url: '',
    ssh_url: '',
    clone_url: '',
    svn_url: '',
    homepage: '',
    size: 0,
    stargazers_count: 0,
    watchers_count: 0,
    language: '',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: false,
    has_pages: true,
    forks_count: 0,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: {
      key: '',
      name: '',
      spdx_id: '',
      url: '',
      node_id: ''
    },
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: '',
    score: 0
  };
;
  constructor() { }

  ngOnInit(): void {
  }

}
