version: "3.7"
services:
  db: 
    image: mysql
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - ./db/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 202cb962ac59075b964b07152d234b70
      restart: always

  # api:
  #   build: ./api
  #   container_name: node-container
  #   restart: always
  #   volumes:
  #     - ./api:/home/node/app
  #   ports:
  #     - "4000:4000"
  #   depends_on: 
  #     - db
  #   environment:
  #     restart: always
