swagger: "2.0"
info:
  description: Rest Api contendo informações sobre automoveis
  version: "0.0.1"
  title: Automoveis API
basePath: "/"
schemes:
  - "http"
paths:
  /automoveis:
    get:
      summary: "Listagem de automovel com paginação"
      parameters:
        - in: query
          name: limit
          type: integer
          required: false
          description: Quantidade de resultados por pagina

        - in: query
          name: page
          type: integer
          required: false
          description: Número da página

        - in: query
          name: ano
          type: integer
          required: false
          description: "traz somente os automoveis com o ano informado"

        - in: query
          name: placa
          type: string
          required: false
          description: "traz somente os automoveis com a placa informado"

        - in: query
          name: cor
          type: string
          required: false
          description: "traz somente os automoveis contendo a cor informada"

        - in: query
          name: marca
          type: string
          required: false
          description: "traz somente os automoveis contendo a marca informada"

        - in: query
          name: modelo
          type: string
          required: false
          description: "traz somente os automoveis contendo o modelo informado"

      produces:
        - "application/json"
      responses:
        200:
          description: "success"
          schema:
            $ref: "#/definitions/automovel"
        204:
          description: "no content"

        500:
            description: "server error"

    post:
      summary: "Insere um novo automóvel"
      parameters:
        - in: body
          name: automovel
          required: true
          schema:
            $ref: "#/definitions/automovel"

      responses:
        201:
          description: "created"
        500:
          description: "server error"





definitions:
  automovel:
    type: "object"
    properties:
      id:
        type: "number"
      placa:
        type: "string"
      ano:
        type: "number"
      marca:
        type: "number"
      modelo:
        type: "number"