swagger: "2.0"
info:
  description: Rest Api contendo informações sobre automoveis
  version: "0.0.1"
  title: Automóveis API
schemes:
  - "http"
paths:
  /automoveis:
    get:
      summary: "Listagem de automóveis com paginação"
      tags:
        - Automóveis
      parameters:
        - in: query
          name: limit
          type: integer
          required: false
          description: Quantidade de resultados por página

        - in: query
          name: page
          type: integer
          required: false
          description: Número da página

        - in: query
          name: ano
          type: integer
          required: false
          description: "traz somente os automóveis com o ano informado"

        - in: query
          name: placa
          type: string
          required: false
          description: "traz somente os automóveis com a placa informada"

        - in: query
          name: cor
          type: string
          required: false
          description: "traz somente os automóveis contendo a cor informada"

        - in: query
          name: marca
          type: string
          required: false
          description: "traz somente os automóveis contendo a marca informada"

        - in: query
          name: modelo
          type: string
          required: false
          description: "traz somente os automóveis contendo o modelo informado"

      produces:
        - "application/json"
      responses:
        200:
          description: "success"
          schema:
            $ref: "#/definitions/automovel"
        204:
          description: "no content"

        500:
          description: "server error"

    post:
      summary: "Insere um novo automóvel"
      tags:
        - Automóveis
      parameters:
        - in: body
          name: automovel
          required: true
          schema:
            $ref: "#/definitions/automovel"

      responses:
        201:
          description: "created"
        409:
          description: "Já existe um automóvel com o id informado"
        500:
          description: "server error"

  /automoveis/{id}:
    get:
      tags:
        - Automóveis
      summary: "Recupera um automóvel pelo id"
      parameters:
        - in: path
          name: id
          type: integer
          required: true
          description: id do automóvel
      responses:
        200:
          description: "sucess"
        204:
          description: "não encontrado"
        500:
          description: "server error"

    delete:
      summary: "Exclui um automóvel"
      tags:
        - Automóveis
      parameters:
        - in: path
          name: id
          type: integer
          required: true
          description: id do automóvel
      responses:
        200:
          description: "sucess"
        404:
          description: "Nenhum registro afetado"
        500:
          description: "server error"

    put:
      tags:
        - Automóveis
      summary: "Atualiza um automóvel"
      description: "Atualiza todos os campos do automóvel"
      parameters:
        - in: path
          name: id
          type: integer
          required: true
          description: id do automóvel

        - in: body
          name: automovel
          required: true
          schema:
            $ref: "#/definitions/automovel"

      responses:
        202:
          description: "sucess"
        404:
          description: "Nenhum registro afetado"
        500:
          description: "server error"

    patch:
      tags:
        - Automóveis
      summary: "Atualiza um automóvel parcialmente"
      description: "Atualiza so campos que foram informados os outros permanecem inalterados"
      parameters:
        - in: path
          name: id
          type: integer
          required: true
          description: id do automóvel

        - in: body
          name: automovel
          required: true
          schema:
            $ref: "#/definitions/automovel"

      responses:
        202:
          description: "sucess"
        404:
          description: "Nenhum registro afetado"
        500:
          description: "server error"

definitions:
  automovel:
    type: "object"
    properties:
      id:
        type: "number"
      placa:
        type: "string"
      ano:
        type: "number"
      marca:
        type: "string"
      modelo:
        type: "string"