version: "3"
services:
  mongo:
    image: mongo
    ports:
      - "27017-27019:27017-27019"
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
  web:
    build:
      context: .
    command: npm start
    volumes:
      - ".:/app"
    ports:
      - 3000:3000
      - 3001:3001
